import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Kelembagaan | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function KelembagaanLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Kelembagaan'}
				textMain={'Kelembagaan'}
				textBottom={'Kelembagaan'}
			/>
			{children}
		</>
	);
}
