import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Potensi Desa | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function PotensiLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Potensi Desa'}
				textMain={'Potensi Desa'}
				textBottom={'Tumaratas'}
			/>
			{children}
		</>
	);
}
