import PageTitle from '@/components/PageTitle';

export const metadata = {
	title: 'Berita | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function BeritaLayout({ children }) {
	return (
		<>
			<PageTitle title={'Berita'} />
			{children}
		</>
	);
}
