import PageTitle from '@/components/PageTitle';

export const metadata = {
	title: 'Pembangunan Desa | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function PembangunanDesaLayout({ children }) {
	return (
		<>
			<PageTitle title={'Pembangunan Desa'} />
			{children}
		</>
	);
}
