import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Peta Desa | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function PetaDesaLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Peta Desa'}
				textMain={'Peta Desa'}
				textBottom={'Tumaratas'}
			/>
			{children}
		</>
	);
}
