import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Sarana dan Prasarana | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function SaranadanPrasaranaLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Sarana'}
				textMain={'Sarana dan Prasarana'}
				textBottom={'Prasarana'}
			/>
			{children}
		</>
	);
}
