import { Providers } from '@/lib/providers';
import MainNav from '@/components/navbar/MainNav';
import Footer from '@/components/Footer';
import LatestPost from '@/components/feature/LatestPost';

export const metadata = {
	title: 'Desa Tumaratas',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<MainNav />
					{children}
					<LatestPost />
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
