import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Struktur Organisasi | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function StrukturOrganisasiLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Struktur'}
				textMain={'Struktur Organisasi'}
				textBottom={'Organisasi'}
			/>
			{children}
		</>
	);
}
