import PageTitle from '@/components/PageTitle';

export const metadata = {
	title: 'Keuangan Desa | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function KeuanganDesaLayout({ children }) {
	return (
		<>
			<PageTitle title={'Keuangan Desa'} />
			{children}
		</>
	);
}
