import HeroTitle from '@/components/HeroTitle';

export const metadata = {
	title: 'Visi dan Misi | Desa Tumaratas',
	description: 'Generated by create next app',
};

export default function VisidanMisiLayout({ children }) {
	return (
		<>
			<HeroTitle
				textTop={'Visi Misi Desa'}
				textMain={'Visi dan Misi'}
				textBottom={'Tumaratas'}
			/>
			{children}
		</>
	);
}
